__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("KlibApiKt")))
@interface SharedKlibApiKt : SharedBase
+ (id<SharedKotlinx_datetimeClock>)return_kotlinx_datetime_Clock __attribute__((swift_name("return_kotlinx_datetime_Clock()")));
+ (SharedKotlinx_datetimeClockSystem *)return_kotlinx_datetime_Clock_System __attribute__((swift_name("return_kotlinx_datetime_Clock_System()")));
+ (SharedKotlinx_datetimeDatePeriod *)return_kotlinx_datetime_DatePeriod __attribute__((swift_name("return_kotlinx_datetime_DatePeriod()")));
+ (SharedKotlinx_datetimeDateTimeArithmeticException *)return_kotlinx_datetime_DateTimeArithmeticException __attribute__((swift_name("return_kotlinx_datetime_DateTimeArithmeticException()")));
+ (SharedKotlinx_datetimeDateTimePeriod *)return_kotlinx_datetime_DateTimePeriod __attribute__((swift_name("return_kotlinx_datetime_DateTimePeriod()")));
+ (SharedKotlinx_datetimeDateTimeUnit *)return_kotlinx_datetime_DateTimeUnit __attribute__((swift_name("return_kotlinx_datetime_DateTimeUnit()")));
+ (SharedKotlinx_datetimeDateTimeUnitDateBased *)return_kotlinx_datetime_DateTimeUnit_DateBased __attribute__((swift_name("return_kotlinx_datetime_DateTimeUnit_DateBased()")));
+ (SharedKotlinx_datetimeDateTimeUnitDayBased *)return_kotlinx_datetime_DateTimeUnit_DayBased __attribute__((swift_name("return_kotlinx_datetime_DateTimeUnit_DayBased()")));
+ (SharedKotlinx_datetimeDateTimeUnitMonthBased *)return_kotlinx_datetime_DateTimeUnit_MonthBased __attribute__((swift_name("return_kotlinx_datetime_DateTimeUnit_MonthBased()")));
+ (SharedKotlinx_datetimeDateTimeUnitTimeBased *)return_kotlinx_datetime_DateTimeUnit_TimeBased __attribute__((swift_name("return_kotlinx_datetime_DateTimeUnit_TimeBased()")));
+ (SharedKotlinx_datetimeDayOfWeek *)return_kotlinx_datetime_DayOfWeek __attribute__((swift_name("return_kotlinx_datetime_DayOfWeek()")));
+ (SharedKotlinx_datetimeFixedOffsetTimeZone *)return_kotlinx_datetime_FixedOffsetTimeZone __attribute__((swift_name("return_kotlinx_datetime_FixedOffsetTimeZone()")));
+ (SharedKotlinx_datetimeIllegalTimeZoneException *)return_kotlinx_datetime_IllegalTimeZoneException __attribute__((swift_name("return_kotlinx_datetime_IllegalTimeZoneException()")));
+ (SharedKotlinx_datetimeInstant *)return_kotlinx_datetime_Instant __attribute__((swift_name("return_kotlinx_datetime_Instant()")));
+ (SharedKotlinx_datetimeLocalDate *)return_kotlinx_datetime_LocalDate __attribute__((swift_name("return_kotlinx_datetime_LocalDate()")));
+ (SharedKotlinx_datetimeLocalDateTime *)return_kotlinx_datetime_LocalDateTime __attribute__((swift_name("return_kotlinx_datetime_LocalDateTime()")));
+ (SharedKotlinx_datetimeLocalDateTimeFormats *)return_kotlinx_datetime_LocalDateTime_Formats __attribute__((swift_name("return_kotlinx_datetime_LocalDateTime_Formats()")));
+ (SharedKotlinx_datetimeLocalDateFormats *)return_kotlinx_datetime_LocalDate_Formats __attribute__((swift_name("return_kotlinx_datetime_LocalDate_Formats()")));
+ (SharedKotlinx_datetimeLocalTime *)return_kotlinx_datetime_LocalTime __attribute__((swift_name("return_kotlinx_datetime_LocalTime()")));
+ (SharedKotlinx_datetimeLocalTimeFormats *)return_kotlinx_datetime_LocalTime_Formats __attribute__((swift_name("return_kotlinx_datetime_LocalTime_Formats()")));
+ (SharedKotlinx_datetimeMonth *)return_kotlinx_datetime_Month __attribute__((swift_name("return_kotlinx_datetime_Month()")));
+ (SharedKotlinx_datetimeTimeZone *)return_kotlinx_datetime_TimeZone __attribute__((swift_name("return_kotlinx_datetime_TimeZone()")));
+ (SharedKotlinx_datetimeUtcOffset *)return_kotlinx_datetime_UtcOffset __attribute__((swift_name("return_kotlinx_datetime_UtcOffset()")));
+ (SharedKotlinx_datetimeUtcOffsetFormats *)return_kotlinx_datetime_UtcOffset_Formats __attribute__((swift_name("return_kotlinx_datetime_UtcOffset_Formats()")));
+ (SharedKotlinx_datetimeAmPmMarker *)return_kotlinx_datetime_format_AmPmMarker __attribute__((swift_name("return_kotlinx_datetime_format_AmPmMarker()")));
+ (SharedKotlinx_datetimeDateTimeComponents *)return_kotlinx_datetime_format_DateTimeComponents __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeComponents()")));
+ (SharedKotlinx_datetimeDateTimeComponentsFormats *)return_kotlinx_datetime_format_DateTimeComponents_Formats __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeComponents_Formats()")));
+ (id<SharedKotlinx_datetimeDateTimeFormat>)return_kotlinx_datetime_format_DateTimeFormat __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormat()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilder>)return_kotlinx_datetime_format_DateTimeFormatBuilder __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilderWithDate>)return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDate __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDate()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilderWithDateTime>)return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDateTime __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDateTime()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilderWithDateTimeComponents>)return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDateTimeComponents __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder_WithDateTimeComponents()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilderWithTime>)return_kotlinx_datetime_format_DateTimeFormatBuilder_WithTime __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder_WithTime()")));
+ (id<SharedKotlinx_datetimeDateTimeFormatBuilderWithUtcOffset>)return_kotlinx_datetime_format_DateTimeFormatBuilder_WithUtcOffset __attribute__((swift_name("return_kotlinx_datetime_format_DateTimeFormatBuilder_WithUtcOffset()")));
+ (SharedKotlinx_datetimeDayOfWeekNames *)return_kotlinx_datetime_format_DayOfWeekNames __attribute__((swift_name("return_kotlinx_datetime_format_DayOfWeekNames()")));
+ (SharedKotlinx_datetimeMonthNames *)return_kotlinx_datetime_format_MonthNames __attribute__((swift_name("return_kotlinx_datetime_format_MonthNames()")));
+ (SharedKotlinx_datetimePadding *)return_kotlinx_datetime_format_Padding __attribute__((swift_name("return_kotlinx_datetime_format_Padding()")));
+ (SharedKotlinx_datetimeDateBasedDateTimeUnitSerializer *)return_kotlinx_datetime_serializers_DateBasedDateTimeUnitSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DateBasedDateTimeUnitSerializer()")));
+ (SharedKotlinx_datetimeDatePeriodComponentSerializer *)return_kotlinx_datetime_serializers_DatePeriodComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DatePeriodComponentSerializer()")));
+ (SharedKotlinx_datetimeDatePeriodIso8601Serializer *)return_kotlinx_datetime_serializers_DatePeriodIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DatePeriodIso8601Serializer()")));
+ (SharedKotlinx_datetimeDateTimePeriodComponentSerializer *)return_kotlinx_datetime_serializers_DateTimePeriodComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DateTimePeriodComponentSerializer()")));
+ (SharedKotlinx_datetimeDateTimePeriodIso8601Serializer *)return_kotlinx_datetime_serializers_DateTimePeriodIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DateTimePeriodIso8601Serializer()")));
+ (SharedKotlinx_datetimeDateTimeUnitSerializer *)return_kotlinx_datetime_serializers_DateTimeUnitSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DateTimeUnitSerializer()")));
+ (SharedKotlinx_datetimeDayBasedDateTimeUnitSerializer *)return_kotlinx_datetime_serializers_DayBasedDateTimeUnitSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DayBasedDateTimeUnitSerializer()")));
+ (SharedKotlinx_datetimeDayOfWeekSerializer *)return_kotlinx_datetime_serializers_DayOfWeekSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_DayOfWeekSerializer()")));
+ (SharedKotlinx_datetimeFixedOffsetTimeZoneSerializer *)return_kotlinx_datetime_serializers_FixedOffsetTimeZoneSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_FixedOffsetTimeZoneSerializer()")));
+ (SharedKotlinx_datetimeInstantComponentSerializer *)return_kotlinx_datetime_serializers_InstantComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_InstantComponentSerializer()")));
+ (SharedKotlinx_datetimeInstantIso8601Serializer *)return_kotlinx_datetime_serializers_InstantIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_InstantIso8601Serializer()")));
+ (SharedKotlinx_datetimeLocalDateComponentSerializer *)return_kotlinx_datetime_serializers_LocalDateComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalDateComponentSerializer()")));
+ (SharedKotlinx_datetimeLocalDateIso8601Serializer *)return_kotlinx_datetime_serializers_LocalDateIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalDateIso8601Serializer()")));
+ (SharedKotlinx_datetimeLocalDateTimeComponentSerializer *)return_kotlinx_datetime_serializers_LocalDateTimeComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalDateTimeComponentSerializer()")));
+ (SharedKotlinx_datetimeLocalDateTimeIso8601Serializer *)return_kotlinx_datetime_serializers_LocalDateTimeIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalDateTimeIso8601Serializer()")));
+ (SharedKotlinx_datetimeLocalTimeComponentSerializer *)return_kotlinx_datetime_serializers_LocalTimeComponentSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalTimeComponentSerializer()")));
+ (SharedKotlinx_datetimeLocalTimeIso8601Serializer *)return_kotlinx_datetime_serializers_LocalTimeIso8601Serializer __attribute__((swift_name("return_kotlinx_datetime_serializers_LocalTimeIso8601Serializer()")));
+ (SharedKotlinx_datetimeMonthBasedDateTimeUnitSerializer *)return_kotlinx_datetime_serializers_MonthBasedDateTimeUnitSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_MonthBasedDateTimeUnitSerializer()")));
+ (SharedKotlinx_datetimeMonthSerializer *)return_kotlinx_datetime_serializers_MonthSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_MonthSerializer()")));
+ (SharedKotlinx_datetimeTimeBasedDateTimeUnitSerializer *)return_kotlinx_datetime_serializers_TimeBasedDateTimeUnitSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_TimeBasedDateTimeUnitSerializer()")));
+ (SharedKotlinx_datetimeTimeZoneSerializer *)return_kotlinx_datetime_serializers_TimeZoneSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_TimeZoneSerializer()")));
+ (SharedKotlinx_datetimeUtcOffsetSerializer *)return_kotlinx_datetime_serializers_UtcOffsetSerializer __attribute__((swift_name("return_kotlinx_datetime_serializers_UtcOffsetSerializer()")));
@end